name: Linters

# This action works with pull requests and pushes
on:
  pull_request:
  push:
    branches:
    - master
    - ci-linters 

jobs:
  curlylint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        # Make sure the actual branch is checked out when running on pull requests
        ref: ${{ github.head_ref }}
        
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
            
    - name: Install curlylint
      run: pip3 install curlylint
    - name: Run curlylint
      run: curlylint --parse-only $GITHUB_WORKSPACE/
     
  prettier:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        # Make sure the actual branch is checked out when running on pull requests
        ref: ${{ github.head_ref }}
        
    - name: Prettify code
      uses: creyD/prettier_action@v3.1
      with:
        prettier_options: --write **/*.{css,js,md}
        dry: True
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
